### ISSUE TITLE
Crashig on start

### ISSUE THREAD

**Issue by Luisinhi010** [SawPorts/QT-Psyched-Up-Edition#3]
### Describe your bug here.

Every time i try to enter the game its justs show the crash log, for some reason gfDanceTitle.json isn't loading or something 
![Screenshot_20230109-154817](https://user-images.githubusercontent.com/91190561/211385617-5d17e869-9820-4c83-bdd1-a6c01bc136bf.jpg)

### Command Prompt/Terminal logs (if existing)

```bash
/opt/hostedtoolcache/haxe/4.2.5/x64/std/cpp/_std/sys/io/File.hx (line 30)
TitleState.hx (line 121)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 360)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1417)
openfl/display/DisplayObject.hx (line 1478)
openfl/display/DisplayObjectContainer.hx (line 266)
openfl/display/DisplayObjectContainer.hx (line 155)
Main.hx (line 22)
ApplicationMain.hx (line 317)
[file_contents,/storage/emulated/0/.QT/assets/images/gfDanceTitle.json]
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah

**Comment by Luisinhi010** [comment]
the line being referenced is "titleJSON = Json.parse(File.getContent(path));"
 I don't know how I can help to fix it because I don't know how cell phones load files but I'll try.

**Comment by MAJigsaw77** [comment]
If you didn't copied the assets

**Comment by Luisinhi010** [comment]
> If you didn't copied the assets

i copied.

**Comment by Luisinhi010** [comment]
i folloed the tutorial

**Comment by Luisinhi010** [comment]
this only happens on this port

**Comment by Luisinhi010** [comment]
hey, why does it have duplicated folders named "assets"?

**Comment by Luisinhi010** [comment]
just asking since i got confused
